# Generated by Django 3.2.14 on 2022-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='ability',
            field=models.CharField(blank=True, choices=[('', 'Choose your level'), ('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=1),
        ),
    ]
