# Generated by Django 3.2.14 on 2022-08-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('', 'Pick a lesson type'), ('H', 'Home visit'), ('O', 'Online'), ('S', 'At the Studio')], max_length=1),
        ),
    ]
