# Generated by Django 3.2.14 on 2022-08-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_alter_booking_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="learner",
            new_name="user",
        ),
    ]
